# oprator boolean (and)
import os
os.system("cls")
nilai = True
nilai2 = False
output = (nilai and nilai)
output2 = (nilai and nilai2)
output3 = (nilai2 and nilai)
output4 = (nilai2 and nilai2)
print("oprator (and) : ")
print("-"*45)
print("|{:<10}|{:<10}|{:<20}|".format("nilai1", "nilai2", "nilai1 and nilai2"))
print("-"*45)
print("|{:<10}|{:<10}|{:<20}|".format(nilai, nilai, output))
print("|{:<10}|{:<10}|{:<20}|".format(nilai, nilai2, output2))
print("|{:<10}|{:<10}|{:<20}|".format(nilai2, nilai, output3))
print("|{:<10}|{:<10}|{:<20}|".format(nilai2, nilai2, output4))
print("-"*45)
print()
# oprator boolean (or)
output = (nilai or nilai)
output2 = (nilai or nilai2)
output3 = (nilai2 or nilai)
output4 = (nilai2 or nilai2)
print("oprator (or) : ")
print("-"*45)
print("|{:<10}|{:<10}|{:<20}|".format("nilai1", "nilai2", "nilai1 and nilai2"))
print("-"*45)
print("|{:<10}|{:<10}|{:<20}|".format(nilai, nilai, output))
print("|{:<10}|{:<10}|{:<20}|".format(nilai, nilai2, output2))
print("|{:<10}|{:<10}|{:<20}|".format(nilai2, nilai, output3))
print("|{:<10}|{:<10}|{:<20}|".format(nilai2, nilai2, output4))
print("-"*45)
print()
# oprator (not)
output = (not(nilai))
output2 = (not(nilai))
output3 = (not(nilai2))
output4 = (not(nilai2))
print("oprator (not) : ")
print("-"*25)
print("|{:<10}|{:<10}|".format("nilai1", "nilai2", "nilai1 and nilai2"))
print("-"*25)
print("|{:<10}|{:<10}|".format(nilai, output))
print("|{:<10}|{:<10}|".format(nilai, output2))
print("|{:<10}|{:<10}|".format(nilai2, output3))
print("|{:<10}|{:<10}|".format(nilai2, output4))
print("-"*25)
